# -*- coding: utf-8 -*-
"""recommend_games_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vB0ReWFVuSqN1mtNGTxozFgEe9b_xwkM
"""

import gradio as gr
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from googleapiclient.discovery import build
from openai import OpenAI
import os
import json

# --- 0. (중요) API 키 설정 ---
# 허깅페이스 스페이스의 'Settings' -> 'Repository secrets'에
# 3개의 키를 저장해야 합니다.
YOUR_API_KEY = os.environ.get("API_KEY", "YOUR_API_KEY_HERE")
YOUR_CX      = os.environ.get("CX", "YOUR_CX_HERE")
YOUR_OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "YOUR_OPENAI_API_KEY_HERE")

if YOUR_API_KEY == "YOUR_API_KEY_HERE":
    print("⚠️ 경고: Google API 키(API_KEY)를 Secrets에 추가하세요.")
if YOUR_CX == "YOUR_CX_HERE":
    print("⚠️ 경고: Google CX ID(CX)를 Secrets에 추가하세요.")
if YOUR_OPENAI_API_KEY == "YOUR_OPENAI_API_KEY_HERE":
    print("⚠️ 경고: OpenAI API 키(OPENAI_API_KEY)를 Secrets에 추가하세요.")

# --- 1. 모델 및 DB 로드 (앱 실행 시 1회) ---
print("SentenceTransformer 모델 로드 중...")
model_name = 'paraphrase-mpnet-base-v2'
sbert_model = SentenceTransformer(model_name)
print("SBERT 모델 로드 완료.")

print("OpenAI 클라이언트 초기화 중...")
try:
    openai_client = OpenAI(api_key=YOUR_OPENAI_API_KEY)
    print("OpenAI 클라이언트 로드 완료.")
except Exception as e:
    print(f"OpenAI 클라이언트 초기화 오류: {e}")
    openai_client = None

print("게임 벡터 DB 및 메타데이터 로드 중...")
try:
    game_vectors = np.load("game_text_vectors.npy")
    games_df = pd.read_csv("preprocessed_games_2.csv")

    # [수정] appid가 정수형(int)인지 확인 (URL 생성에 필수)
    if 'appid' not in games_df.columns:
        raise Exception("preprocessed_games_2.csv에 'appid' 컬럼이 없습니다.")
    games_df['appid'] = games_df['appid'].astype(int)

    # [1단계]에서 생성한 'meta_text'가 preprocessed_games_2.csv에 없을 수 있으므로,
    # LLM에 전달할 '설명' 컬럼을 여기서 다시 만듭니다.
    def create_meta_text(row):
        name = str(row.get('original_name', ''))
        genres = str(row.get('genres', '')).replace('|', ' ').replace('[', '').replace(']', '').replace("'", "")
        tags = str(row.get('tags', '')).replace('[', '').replace(']', '').replace("'", "")
        desc = str(row.get('short_description', ''))
        if not genres and not tags and not desc: return name
        return f"{name} {genres} {tags} {desc}"

    games_df['llm_desc'] = games_df.apply(create_meta_text, axis=1)

    print(f"{len(games_df)}개의 게임 정보 로드 완료.")
except FileNotFoundError:
    print("오류: game_text_vectors.npy 또는 preprocessed_games_2.csv 파일을 찾을 수 없습니다.")
    game_vectors = None
    games_df = None
except Exception as e:
    print(f"게임 데이터 로드 중 치명적 오류: {e}")
    game_vectors = None
    games_df = None

# --- 2. RAG (Google 검색) 함수 ---
def get_google_search_summary(movie_title, api_key, cx):
    if api_key == "YOUR_API_KEY_HERE" or cx == "YOUR_CX_HERE":
        return None, "API_KEY_NOT_SET"
    try:
        service = build("customsearch", "v1", developerKey=api_key)
        query = f"{movie_title} movie plot summary and genre"
        res = service.cse().list(
            q=query, cx=cx, num=1, siteSearch='imdb.com'
        ).execute()
        if 'items' in res and len(res['items']) > 0:
            snippet = res['items'][0].get('snippet', '')
            title = res['items'][0].get('title', '')
            return f"{title} {snippet}", "SUCCESS"
        else:
            return None, "NO_RESULTS"
    except Exception as e:
        print(f"[RAG Error] Google Search failed: {e}")
        return None, "API_ERROR"

# --- 3. LLM (GPT) 재정렬 함수 (신규) ---
def call_gpt_for_reranking(movie_title, movie_summary, candidate_games):
    """
    GPT를 호출하여 게임 리스트를 재정렬하고 추천 이유를 생성합니다.
    candidate_games: [{"title": "Game A", "desc": "Description A"}, ...]
    """
    if not openai_client or YOUR_OPENAI_API_KEY == "YOUR_OPENAI_API_KEY_HERE":
        raise Exception("OpenAI API 키가 설정되지 않았습니다.")

    # LLM에게 전달할 게임 후보 리스트 생성
    game_list_str = ""
    for i, game in enumerate(candidate_games):
        # LLM 프롬프트가 너무 길어지지 않게 설명을 300자로 제한
        game_list_str += f"{i+1}. GAME_TITLE: {game['title']}\n   DESCRIPTION: {game['desc'][:300]}...\n\n"

    # (사용자가 제공한) 시스템 프롬프트
    system_prompt = """You are an expert in recommending games based on movies. Your goal is to re-rank a list of candidate games based on how well their genre or atmosphere matches the movie the user watched.
You must analyze the movie's plot and genre, along with each game's description and tags. Focus on matching the theme, atmosphere, genre, and core elements between the movie and the games.
You must output *only* a valid JSON object in the specified format."""

    user_prompt = f"""
A user liked the movie: '{movie_title}'
Here is the movie's summary (from RAG):
--- MOVIE SUMMARY ---
{movie_summary}
---------------------

Here are the {len(candidate_games)} candidate games (from SBERT similarity) that need re-ranking:
--- CANDIDATE GAMES ---
{game_list_str}
-----------------------

Your task:
1. "Judge": Re-rank all {len(candidate_games)} games. List their original titles from most relevant to least relevant to the movie.
2. "Generate": Provide a brief, one-sentence reason in Korean for why you selected the #1 ranked game and why your #1 ranked game is a good match for the movie.

Provide your output *only* in the following JSON format:
{{
  "re_ranked_games": ["Game Title 1", "Game Title 2", ...],
  "top_recommendation_reason": "Your one-sentence reason here (in Korean)."
}}
"""

    try:
        completion = openai_client.chat.completions.create(
            model="gpt-3.5-turbo-1106", # JSON 모드를 지원하는 모델
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            response_format={"type": "json_object"},
            temperature=0.2
        )

        response_content = completion.choices[0].message.content
        response_json = json.loads(response_content)

        re_ranked_list = response_json.get("re_ranked_games", [])
        reason = response_json.get("top_recommendation_reason", "")

        return re_ranked_list, reason, "SUCCESS"

    except Exception as e:
        print(f"[LLM Error] GPT Reranking failed: {e}")
        return None, None, f"LLM_ERROR: {e}"

# --- 4. 추천 시스템 함수 (핵심 로직 수정) ---
def recommend_games(movie_title, top_k=5):
    if game_vectors is None or games_df is None:
        return "오류: 서버에 게임 DB가 로드되지 않았습니다. 관리자에게 문의하세요."
    if not openai_client:
        return "오류: OpenAI 클라이언트가 로드되지 않았습니다. API 키를 확인하세요."

    # 1. RAG: 영화 줄거리 가져오기
    rag_summary, g_status = get_google_search_summary(movie_title, YOUR_API_KEY, YOUR_CX)

    query_text = ""
    rag_status_msg = ""

    if g_status == "SUCCESS":
        query_text = rag_summary
        rag_status_msg = f"✅ RAG (Google): IMDB에서 '{movie_title}' 요약을 가져왔습니다.\n\n[검색된 요약]\n{rag_summary}\n"
    elif g_status == "API_KEY_NOT_SET":
        return "오류: Google API 키 또는 CX ID가 서버에 설정되지 않았습니다."
    else:
        query_text = movie_title
        rag_status_msg = f"⚠️ RAG (Google) 실패({g_status}): 입력한 제목 '{movie_title}'(으)로 대체 검색합니다.\n"

    # 2. 1차 추천 (SBERT): 영화 줄거리를 벡터로 변환
    movie_vector = sbert_model.encode([query_text]) # 2D 배열 [[...]]

    # 3. SBERT 유사도 계산 -> Top 15 후보 선정
    N_CANDIDATES = 15 # LLM에게 15개의 후보를 줍니다.
    sim_scores = cosine_similarity(movie_vector, game_vectors).flatten()
    top_indices_sbert = sim_scores.argsort()[::-1][:N_CANDIDATES]

    # 4. LLM 재정렬을 위한 후보 리스트 준비
    candidate_games_info = []
    # [수정됨] LLM 실패 시 Fallback을 위해 appid와 SBERT 점수를 모두 저장하는 Map 생성
    sbert_fallback_map = {}

    for idx in top_indices_sbert:
        game_row = games_df.iloc[idx]
        game_title = game_row['original_name']
        game_desc = game_row['llm_desc']
        game_appid = game_row['appid']

        # LLM에게 전달할 정보
        candidate_games_info.append({"title": game_title, "desc": game_desc})

        # LLM이 실패하거나, LLM의 결과를 다시 매핑할 때 사용할 내부 지도
        sbert_fallback_map[game_title] = {
            "appid": game_appid,
            "score": sim_scores[idx] # SBERT 점수 (참고용)
        }

    # 5. 2차 추천 (LLM) 호출
    llm_reason_msg = ""
    final_title_list = []

    try:
        re_ranked_list, reason, llm_status = call_gpt_for_reranking(
            movie_title, query_text, candidate_games_info
        )

        if llm_status == "SUCCESS":
            llm_reason_msg = f"\n{reason}\n"
            final_title_list = re_ranked_list[:top_k] # LLM이 재정렬한 순서
        else:
            # LLM 실패 시 SBERT 순위로 대체 (Fallback)
            llm_reason_msg = f"⚠️ LLM(GPT) 재정렬 실패({llm_status}). SBERT 유사도 순서로 대체합니다.\n"
            final_title_list = list(sbert_fallback_map.keys())[:top_k]

    except Exception as e:
        # OpenAI API 키가 없거나 기타 예외
        llm_reason_msg = f"⚠️ LLM(GPT) 호출 오류: {e}\nSBERT 유사도 순서로 대체합니다.\n"
        final_title_list = list(sbert_fallback_map.keys())[:top_k]

    # 6. 최종 결과 포맷팅
    final_output = ""

    final_output += f"""
    <p style='font-size:18px; font-family:"Pretendard","Noto Sans KR",sans-serif; line-height:1.6;'>
        💬 <b>추천의 이유</b><br>
        {llm_reason_msg}
    </p>
    <br>
    """

    final_output += f"""
    <div style='background:#252525; color:white; border-radius:10px; padding:10px 15px;
                box-shadow:0 0 6px rgba(255,255,255,0.05); border:1px solid #333;
                font-size:16px; line-height:1.6; font-family:"Pretendard","Noto Sans KR",sans-serif;'>

    🎮 <b style='color:white;'>추천 결과</b><br>
    <hr style='border:none; height:1px; background:linear-gradient(to right, #555, #ccc, #555); margin:10px 0;'>
    """

    for i, title in enumerate(final_title_list):
        # 4번에서 만든 sbert_fallback_map에서 appid를 찾음
        game_info = sbert_fallback_map.get(title)

        if game_info:
            appid = game_info['appid']
            store_link = f"https://store.steampowered.com/app/{appid}"
            # Steam 공식 이미지 리사이즈/CDN URL
            image_link = f"https://cdn.akamai.steamstatic.com/steam/apps/{appid}/header.jpg"

            final_output += f"""
            <b style='color:white;'>{i+1}. {title}</b><br>
            <a href='{store_link}' target='_blank'>
            <img src='{image_link}' width='400' style='border-radius:8px; margin:6px 0;'>
            </a><br>
            🔗 <a href='{store_link}' target='_blank'>Steam 게임 구매 페이지로 이동</a><br><br>
            """
        else:
            final_output += f"<b>{i+1}. {title}</b><br>(게임 정보를 찾을 수 없습니다.)<br><br>"


    final_output += "</div>"

    return final_output

# --- 5. Gradio 인터페이스 실행 ---
examples = [
    ["Inception", 5],
    ["The Dark Knight", 5],
    ["Dune", 5],
    ["Forrest Gump", 5],
    ["Interstellar", 5],
    ["Oppenheimer", 5]
]

iface = gr.Interface(
    fn=recommend_games,
    inputs=[
        gr.Textbox(
            label="영화 제목",
            placeholder="예: Inception"
        ),
        gr.Slider(
            label="추천할 게임 개수 (Top K)",
            minimum=1,
            maximum=10, # 15개 후보 중 Top 10
            step=1,
            value=5
        )
    ],
    outputs=gr.HTML(
        label="추천 결과",
        #line_breaks=True # Markdown 줄바꿈 활성화
    ),
    title="🎥 영화-게임 추천 시스템",
    description="📽️최근에 재밌게 본 영화랑 비슷한 느낌의 게임도 있을까?",
    examples=examples
)

iface.launch()